# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aeb40e29fb3cc121d55e7b1ed202eb1ba18a5dcd579a99ab4751d99bb1640a89a4e24de2b3b4e1ccdec59134f217f12756a2a836095b9603b72b8d2ecb5d80a6

test:
  secret_key_base: c673e55728023067c1086cf590fad878e63d2d9f1d1c0996bad220efbd84523d576c476b04db12cc0e1e4864d105c3e39617f8e2891e4df7d2bd765fb04919c7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
